import os
from dotenv import load_dotenv

load_dotenv()


WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID")
WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN")
WHATSAPP_VERIFY_TOKEN = os.getenv("WHATSAPP_VERIFY_TOKEN")
BUSINESS_PHONE_NUMBER = os.getenv("BUSINESS_PHONE_NUMBER")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

REPLICATE_API_TOKEN = os.getenv("REPLICATE_API_TOKEN")
HUGGINGFACE_API_TOKEN = os.getenv("HUGGINGFACE_API_TOKEN")

BARBER_PHONE_NUMBER = os.getenv("BARBER_PHONE_NUMBER")
NGROK_URL = os.getenv("NGROK_URL", "")

WHATSAPP_API_VERSION = "v23.0"
WHATSAPP_API_URL = f"https://graph.facebook.com/{WHATSAPP_API_VERSION}/{WHATSAPP_PHONE_NUMBER_ID}/messages"

MAX_SELFIE_RETRIES = 3
MAX_SESSIONS_PER_HOUR = 10
PROCESSING_TIMEOUT_SECONDS = 25
